import { Type } from "@google/genai";

/**
 * Represents the structure of a single comic panel as generated by the model.
 */
export interface GeneratedPanelPrompt {
  panelNumber: number;
  imagePrompt: string;
  caption: string;
}

/**
 * Defines the response schema for the Gemini API when requesting comic panel prompts.
 */
export const COMIC_PANEL_SCHEMA = {
  type: Type.ARRAY,
  items: {
    type: Type.OBJECT,
    properties: {
      panelNumber: { type: Type.NUMBER, description: "The sequential number of the comic panel." },
      imagePrompt: { type: Type.STRING, description: "A detailed visual description for generating the image of this panel." },
      caption: { type: Type.STRING, description: "A short text caption for this comic panel." },
    },
    required: ["panelNumber", "imagePrompt", "caption"],
    propertyOrdering: ["panelNumber", "imagePrompt", "caption"],
  },
};

/**
 * Represents a fully generated comic panel, including its image data.
 */
export interface ComicPanel {
  caption: string;
  imageBase64: string;
}

/**
 * Represents an uploaded image.
 */
export interface UploadedImage {
  base64: string;
  filename: string;
}

/**
 * Defines the different views/states of the application.
 */
export enum AppView {
  UPLOAD = 'upload',
  PREVIEW = 'preview',
  COMIC = 'comic',
}
